name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Install dependencies
        working-directory: ./sam_lambda/arma008_exam/
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build with SAM
        working-directory: ./sam_lambda/arma008_exam/
        run: sam build

      - name: Deploy with SAM
        id: deploy
        working-directory: ./sam_lambda/arma008_exam/
        run: |
          sam deploy --no-confirm-changeset --region ${{ secrets.AWS_REGION }} && echo "NO_CHANGES=false" >> $GITHUB_OUTPUT || (echo "NO_CHANGES=true" >> $GITHUB_OUTPUT && exit 1)

      - name: Check if deployment was skipped
        if: steps.deploy.outputs.NO_CHANGES == 'true'
        run: echo "No changes to deploy, marking as success"
        continue-on-error: true
      
