name: Terraform Deployment

on:
  push:
    branches:
      - main
      - '**'  # This will match all branches

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1  # Specify your desired Terraform version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra  # Path to your Terraform code

      - name: Terraform Plan
        if: github.ref != 'refs/heads/main'  # Run plan for non-main branches
        run: terraform plan
        working-directory: ./infra

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Run apply only for main branch
        run: terraform apply -auto-approve
        working-directory: ./infra

      - name: Terraform Output
        run: terraform output
        working-directory: ./infra